add support for new ShoppingCart and CartItem entities
AntonKurylo/online-book-store-app pull request #13
Opened 2024-08-04 11:24 UTC by AntonKurylo

2024-08-04 16:18 UTC, Elena-Bruyako requested changes
one comment

2024-08-04 16:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +                shoppingCartRepository.findByUserId(authenticatedUserId));
Could you avoid calling shoppingCartRepository.findByUserId twice?

2024-08-06 13:46 UTC, okuzan approved these changes

2024-08-06 13:46 UTC, okuzan commented on src/main/java/mate/academy/repository/cartitem/CartItemRepository.java
> +@Repository
not a mistake but remember that this annotation is optional when we extend JpaRepository

2024-08-06 13:46 UTC, okuzan commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +                });
a bit unwieldy, i would consider extracting to a private method

2024-08-12 19:39 UTC, merged